[17.0] [MIG] stock_available_immediately: Migration to 17.0
OCA/stock-logistics-availability pull request #22
Opened 2024-04-29 06:34 UTC by bizzappdev

2024-04-29 06:51 UTC, rousseldenis commented
/ocabot migration stock_available_immediately

2024-12-02 09:58 UTC, abdounasser202 commented
Any update regarding this PR ?

2024-12-02 10:17 UTC, rousseldenis commented
@bizzappdev Could you remove dependency as merged ? Thanks

2024-12-02 10:17 UTC, rousseldenis approved these changes

2025-01-07 17:24 UTC, carlos-lopez-tecnativa requested changes
LGTM, please check the test

2025-01-07 17:24 UTC, carlos-lopez-tecnativa commented on stock_available_immediately/tests/test_stock_available_immediately.py
> +            product.refresh()
Could you use 
```suggestion
            product.invalidate_recordset()
```

Or
```suggestion
            product.invalidate_recordset(fnames=["immediately_usable_qty"])
```

2025-01-13 16:31 UTC, carlos-lopez-tecnativa commented on stock_available_immediately/tests/test_stock_available_immediately.py
> +            product.refresh()
ping @bizzappdev this might fix the tests.

2025-01-29 13:43 UTC, pedrobaeza commented
Superseded by #36

2025-01-29 13:43 UTC, closed without merging