[MIG] stock_available_unreserved: Migration to 17.0
OCA/stock-logistics-availability pull request #23
Opened 2024-05-07 09:00 UTC by nedaszilinskas

2024-05-07 09:34 UTC, pedrobaeza commented
/ocabot migration stock_available_unreserved

2024-05-07 10:24 UTC, rousseldenis requested changes
Code review

2024-05-07 10:24 UTC, rousseldenis commented on stock_available_unreserved/models/product_template.py
> +        result = self.env.ref("stock.dashboard_open_quants").read()[0]
You should use _for_xml_id() instead.

2024-05-08 07:17 UTC, nedaszilinskas commented on stock_available_unreserved/models/product_template.py
> +        result = self.env.ref("stock.dashboard_open_quants").read()[0]
@rousseldenis Good catch! I changed it.

2025-02-25 17:47 UTC, mageob commented
Is this going to be merged?

2025-06-04 08:30 UTC, sebalix approved these changes

2025-07-02 16:12 UTC, danielduqma commented
Just in case, fix made in https://github.com/OCA/stock-logistics-availability/pull/57 should be applied also to 17.0.

Regards.

2025-12-07 12:45 UTC, closed without merging