[17][FIX]stock_free_quantity: type in views
OCA/stock-logistics-availability pull request #30
Opened 2024-11-29 18:02 UTC by mav-adhoc

There was an error accessing to these views because the field 'type' was not inside the views.

2025-01-21 10:44 UTC, DavidJForgeFlow approved these changes

2025-01-21 10:50 UTC, rousseldenis commented on stock_free_quantity/__manifest__.py
> +    "version": "17.0.1.1.0",
@mav-adhoc Don't update this if you don't have migration scripts

2025-01-21 11:15 UTC, mav-adhoc commented on stock_free_quantity/__manifest__.py
> +    "version": "17.0.1.1.0",
Done!

2025-01-21 12:24 UTC, rousseldenis requested changes

2025-01-21 12:24 UTC, rousseldenis commented on stock_free_quantity/views/product_template_view.xml
> +                    <field name="type" invisible="1" />
IMHO, this is not correct as it is defined in inherited view.

See : [product_product_tree_view](https://github.com/odoo/odoo/blob/17.0/addons/stock/views/product_views.xml#L44)

And particularily : https://github.com/odoo/odoo/blob/17.0/addons/product/views/product_views.xml#L361

2025-01-21 12:32 UTC, mav-adhoc commented on stock_free_quantity/views/product_template_view.xml
> +                    <field name="type" invisible="1" />
Apparently the error exists due to a view of an OCA module (stock_free_quantity), which gives the error because it says that the 'type' field does not have permissions for certain users..

2025-06-04 18:01 UTC, mav-adhoc commented
@rousseldenis Hi! i create this PR because there is an error that exists due to the view of this OCA module (stock_free_quantity), which gives the error because it says that the 'type' field does not have permissions for certain users.

2025-11-03 14:38 UTC, DavidJForgeFlow commented
Could we move this forward and get it merged @rousseldenis ?

2026-04-19 13:12 UTC, closed without merging