[16.0][ADD] stock_available_immediately_exclude_location
OCA/stock-logistics-availability pull request #6
Opened 2023-01-18 13:30 UTC by glitchov

Exclude location(s) from the computation of immediately usable quantity

2023-01-20 09:39 UTC, rousseldenis requested changes

2023-01-20 09:39 UTC, rousseldenis commented on stock_available_immediately_exclude_location/models/product_product.py
> +        res, stock_dict = super(
```suggestion
        res, stock_dict = super()._compute_available_quantities_dict()
```

2023-01-20 09:39 UTC, rousseldenis commented on stock_available_immediately_exclude_location/models/product_product.py
> +        for element in quant_domain:
I don't understand the need of this.

2023-01-20 09:39 UTC, rousseldenis commented on stock_available_immediately_exclude_location/models/product_product.py
> +        for element in quant_domain:
Ok, but I would have added a security feature to be sure no field from stock.quant will arrive in stock.location domain

2023-01-25 08:53 UTC, lmignon approved these changes
LGTM (Code review)

2023-01-25 08:53 UTC, lmignon commented
@rousseldenis Could you update your review PLZ?

2023-01-25 09:00 UTC, rousseldenis commented on stock_available_immediately_exclude_location/models/product_product.py
> +                location_domain.append(
@glitchov This is weird that tests don't pass in this

2023-07-03 06:51 UTC, rousseldenis commented on stock_available_immediately_exclude_location/models/product_product.py
> +                location_domain.append(
@glitchov Could you check my comment ?

2024-04-03 09:01 UTC, jbaudoux approved these changes

2024-04-08 07:40 UTC, jbaudoux commented
@rousseldenis I think this one is good. Can you update your review?

2024-04-08 14:58 UTC, rousseldenis approved these changes

2024-04-08 15:09 UTC, jbaudoux commented
/ocabot merge nobump

2024-04-08 15:15 UTC, merged